name: Build and analyze

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_HOST_URL: http://pvtgk-106-212-15-181.a.free.pinggy.link
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
